server: 
  port: 9528
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
zuul: 
  routes: 
    prefix: /dms
    ignored-services: "*"
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
    
    
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9528.com
    prefer-ip-address: true 

